[package]
name = "dash-cache-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "dash"
# Comment next line in order to run binary crate (main.rs)
crate_type = ["cdylib"]

[dependencies]
jni = "0.20.0"
log = "0.4"
simplelog = "0.11"
chrono = "0.4"
rand = "0.8.5"

[dev-dependencies]
rand = "0.8.5"